name = "syndicate-api-citadel"
main = "dist/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration - runs before deployment
[build]
command = "npm run cf:build"

# Environment variables
[vars]
NODE_ENV = "production"
API_VERSION = "1.0.0"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"

# D1 database binding (optional)
# [[d1_databases]]
# binding = "DB"
# database_name = "syndicate-api"
# database_id = "your_d1_database_id"
