name: Citadel Traceability Audit

on:
  push:
    branches: [ main, master ]
    paths:
      - 'rules/**/*.md'
      - 'bun.yaml'
      - 'openapi.yaml'
      - 'openapi.json'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'rules/**/*.md'
      - 'bun.yaml'
      - 'openapi.yaml'
      - 'openapi.json'

jobs:
  audit-traceability:
    name: Audit API Traceability
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate OpenAPI spec
      run: bun run api:generate

    - name: Run traceability audit
      run: bun run audit:ci

    - name: Upload audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: traceability-audit-results
        path: |
          openapi.yaml
          openapi.json
        retention-days: 30

  validate-spec:
    name: Validate OpenAPI Specification
    runs-on: ubuntu-latest
    needs: audit-traceability

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate and lint OpenAPI spec
      run: |
        bun run api:generate
        bun run api:lint

    - name: Validate OpenAPI spec with spectral
      run: |
        npm install -g @stoplight/spectral-cli
        spectral lint openapi.yaml --ruleset .spectral.yml || true

  test-suite:
    name: Run Test Suite
    runs-on: ubuntu-latest
    needs: audit-traceability

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Run test suite
      run: bun test tests/node-test-examples.test.ts

    - name: Run API tests
      run: bun test api.test.ts
